server:
  port: 8080
  servlet:
    context-path: /netsc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bs_netsc?characterEncoding=utf-8
    username: root
    password:

#    mybatis configuration
mybatis:
  configuration:
    call-setters-on-nulls: true

#图片上传的绝对地址
cbs:
  imagesPath:
    file:/D:/img/

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql
